
name = "trex"
license = "AGPLv3"
licenselink = "https://github.com/tracking-exposed/hugo-theme-trex/blob/master/LICENSE"
description = "Shared hugo theme among *.tracking.exposed websites"
homepage = "https://tracking.exposed"
tags = [ "algorithm accountability", "algorithm analysis", "digital right" ]
features = []
min_version = "0.55"

[author]
  name = "Tracking Exposed contributors"
  homepage = "https://tracking.exposed/about"
